-- ==============================================================================
-- SCHEMA SUPABASE: TechMarket E-commerce & Lab de Segurança em REST APIs
-- ==============================================================================

-- 1. Tabela de Usuários com coluna de status
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  name TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('CUSTOMER', 'SELLER', 'ADMIN')),
  status TEXT NOT NULL DEFAULT 'APPROVED' CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tabela de Produtos do Marketplace
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  price NUMERIC(10, 2) NOT NULL,
  seller_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
  seller_name TEXT NOT NULL,
  category TEXT DEFAULT 'Tecnologia',
  image_url TEXT,
  rating NUMERIC(3, 1) DEFAULT 4.8,
  reviews_count INT DEFAULT 1,
  stock INT DEFAULT 10,
  discount_badge TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Suporte a colunas extras caso a tabela já existisse
ALTER TABLE products ADD COLUMN IF NOT EXISTS category TEXT DEFAULT 'Tecnologia';
ALTER TABLE products ADD COLUMN IF NOT EXISTS image_url TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS rating NUMERIC(3, 1) DEFAULT 4.8;
ALTER TABLE products ADD COLUMN IF NOT EXISTS reviews_count INT DEFAULT 1;
ALTER TABLE products ADD COLUMN IF NOT EXISTS stock INT DEFAULT 10;
ALTER TABLE products ADD COLUMN IF NOT EXISTS discount_badge TEXT;

-- 3. Tabela de Pedidos (Orders & Checkout)
CREATE TABLE IF NOT EXISTS orders (
  id TEXT PRIMARY KEY,
  user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  customer_name TEXT NOT NULL,
  items JSONB NOT NULL,
  subtotal NUMERIC(10, 2) NOT NULL,
  shipping_cost NUMERIC(10, 2) DEFAULT 0,
  discount NUMERIC(10, 2) DEFAULT 0,
  total_amount NUMERIC(10, 2) NOT NULL,
  shipping_address JSONB NOT NULL,
  shipping_method TEXT NOT NULL,
  payment_method TEXT NOT NULL,
  payment_details JSONB DEFAULT '{}'::jsonb,
  status TEXT NOT NULL DEFAULT 'PREPARING',
  tracking_code TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Tabela de Configuração do Sistema (Toggle V1 / V2)
CREATE TABLE IF NOT EXISTS system_config (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==============================================================================
-- SEEDS INICIAIS
-- ==============================================================================

TRUNCATE TABLE orders, products, users, system_config RESTART IDENTITY CASCADE;

-- Inserir Usuários Iniciais
INSERT INTO users (id, username, password, name, role, status) VALUES
  (1, 'alice', '123', 'Alice Compradora', 'CUSTOMER', 'APPROVED'),
  (2, 'joao', '123', 'João Tech (Loja 1)', 'SELLER', 'APPROVED'),
  (3, 'maria', '123', 'Maria Variedades (Loja 2)', 'SELLER', 'APPROVED'),
  (4, 'admin', 'admin123', 'Carlos SysAdmin', 'ADMIN', 'APPROVED');

SELECT setval('users_id_seq', (SELECT MAX(id) FROM users));

-- Inserir Produtos Iniciais
INSERT INTO products (id, name, description, price, seller_id, seller_name, category, image_url, rating, reviews_count, stock, discount_badge) VALUES
  (1, 'MacBook Pro 16" M3 Max', 'Notebook de alta performance com chip M3 Max (16-core CPU, 40-core GPU), 36GB RAM e 1TB SSD Liquid Retina XDR.', 14999.00, 2, 'João Tech (Loja 1)', 'Notebooks', 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80', 4.9, 142, 8, '10% OFF'),
  (2, 'Samsung Galaxy S24 Ultra 512GB', 'Smartphone topo de linha com Galaxy AI, câmera quádrupla de 200MP, S Pen integrada e display Dynamic AMOLED 2X 120Hz.', 7999.00, 3, 'Maria Variedades (Loja 2)', 'Smartphones', 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=800&q=80', 4.8, 98, 15, '15% OFF'),
  (3, 'Monitor Profissional Dell UltraSharp 4K 27"', 'Monitor IPS Black com resolução 4K UHD (3840 x 2160), 98% DCI-P3, USB-C Hub com carregamento de 90W e suporte ergonômico.', 3200.00, 2, 'João Tech (Loja 1)', 'Monitores', 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=800&q=80', 4.9, 64, 12, 'Frete Grátis'),
  (4, 'Headset Sem Fio Sony WH-1000XM5', 'Cancelamento de ruído líder do setor com dois processadores, 8 microfones, áudio Hi-Res sem fio e até 30 horas de bateria.', 2199.00, 3, 'Maria Variedades (Loja 2)', 'Áudio', 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80', 4.9, 210, 20, 'Mais Vendido'),
  (5, 'Teclado Mecânico Wireless Keychron Q1 Pro RGB', 'Teclado mecânico custom premium com estrutura em alumínio CNC usinado, switches Gateron Jupiter Brown e conexão Bluetooth 5.1.', 1150.00, 2, 'João Tech (Loja 1)', 'Periféricos', 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80', 4.7, 45, 10, 'Novo'),
  (6, 'Mouse Sem Fio Logitech MX Master 3S', 'Mouse de precisão ergonômico com sensor Darkfield de 8.000 DPI, cliques silenciosos e roda de rolagem MagSpeed eletromagnética.', 649.00, 3, 'Maria Variedades (Loja 2)', 'Periféricos', 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=800&q=80', 4.9, 312, 25, 'Recomendado'),
  (7, 'Apple iPad Air 11" M2 256GB Wi-Fi', 'Tablet potente com chip M2, tela Liquid Retina brilhante, compatibilidade com Apple Pencil Pro e Magic Keyboard.', 5899.00, 2, 'João Tech (Loja 1)', 'Tablets', 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=800&q=80', 4.8, 78, 6, '5% OFF'),
  (8, 'Placa de Vídeo GeForce RTX 4080 Super 16GB OC', 'Placa gráfica de ponta para jogos em 4K e renderização 3D, arquitetura Ada Lovelace, DLSS 3 e resfriamento Triple Fan.', 7499.00, 3, 'Maria Variedades (Loja 2)', 'Hardware', 'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=800&q=80', 5.0, 52, 4, 'Top Oferta');

SELECT setval('products_id_seq', (SELECT MAX(id) FROM products));

-- Inserir Pedido Inicial para teste
INSERT INTO orders (id, user_id, customer_name, items, subtotal, shipping_cost, discount, total_amount, shipping_address, shipping_method, payment_method, payment_details, status, tracking_code) VALUES
  ('ORD-78412', 1, 'Alice Compradora', '[{"productId": 4, "name": "Headset Sem Fio Sony WH-1000XM5", "price": 2199.00, "quantity": 1, "sellerId": 3, "sellerName": "Maria Variedades (Loja 2)", "imageUrl": "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80"}]'::jsonb, 2199.00, 0.00, 100.00, 2099.00, '{"recipient": "Alice Compradora", "street": "Av. Paulista, 1500, Apto 82", "neighborhood": "Bela Vista", "city": "São Paulo", "state": "SP", "zipCode": "01311-200"}'::jsonb, 'SEDEX Expresso Tech (Frete Grátis)', 'PIX', '{"status": "PAGO"}'::jsonb, 'SHIPPED', 'BR784129841BR');

-- Configurar modo inicial (v1 = Vulnerável)
INSERT INTO system_config (key, value) VALUES ('api_mode', 'v1')
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;
